# Generated by Django 6.0.3 on 2026-03-04 14:53

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('tailor', 'Tailor'), ('customer', 'Customer'), ('admin', 'Admin'), ('support', 'Support')], max_length=10)),
                ('tailor_type', models.CharField(choices=[('regular', 'Regular Tailor'), ('bespoke', 'Bespoke Tailor (Subscribed)')], default='regular', help_text="Only applicable for users with the 'tailor' role.", max_length=20)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('measurements', models.JSONField(blank=True, default=dict)),
                ('measurement_unit', models.CharField(default='metric', max_length=10)),
                ('business_name', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, help_text="e.g. Bridal, Men's Suit", max_length=100)),
                ('starting_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogue_covers', to='media_file.mediafile')),
            ],
        ),
    ]
