# Generated by Django 6.0.3 on 2026-03-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='membership_tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('PREMIUM', 'Premium')], default='FREE', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
