# Generated by Django 6.0.3 on 2026-03-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('tailor', 'Tailor'), ('customer', 'Customer'), ('seller', 'Seller'), ('admin', 'Admin'), ('support', 'Support')], default='customer', help_text='Role of the user in the system', max_length=20),
        ),
    ]
