# Generated by Django 6.0.3 on 2026-03-04 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('cutting', 'Cutting'), ('first_fitting', 'First Fitting'), ('sewing', 'Sewing'), ('second_fitting', 'Second Fitting'), ('finished', 'Finished'), ('delivered', 'Delivered')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('downpayment', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid as downpayment', max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('KES', 'KES')], default='KES', max_length=10)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('due_date', models.DateField(help_text='When the work is meant to be delivered')),
                ('notes', models.TextField(blank=True)),
                ('is_fully_paid', models.BooleanField(default=False, help_text='Has the full payment been completed?')),
                ('date_downpayment_paid', models.DateField(blank=True, help_text='Date the downpayment was actually paid', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='profiles.profile')),
            ],
        ),
    ]
