version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mshoni
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7

  web:
    build: .
    command: gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis