# Generated by Django 6.0.2 on 2026-03-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_bid_is_accepted_bid_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supabase_uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
