# Generated by Django 6.0.3 on 2026-03-05 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_file', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('fabric', 'Fabric'), ('tool', 'Sewing Equipment'), ('thread', 'Threads/Buttons'), ('accessory', 'Bags/Belts/Finished Acc')], default='fabric', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit_type', models.CharField(choices=[('yard', 'Yard'), ('piece', 'Piece')], default='yard', max_length=10)),
                ('quantity', models.FloatField(default=0.0, help_text='Available amount (yards, pieces, etc.)')),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Set to True for Premium/Pro sellers')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_images', to='media_file.mediafile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['-is_featured', '-date_created'],
            },
        ),
    ]
