# Generated by Django 6.0.3 on 2026-03-05 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_escrow'),
        ('tickets', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('payment', 'Payment & Escrow'), ('project', 'Project/Tailoring Dispute'), ('order', 'Material/Seller Order'), ('account', 'Account & Subscription'), ('technical', 'App Technical Issue')], default='technical', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent (Pro/Premium)')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_tickets', to='projects.project'),
        ),
    ]
